### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by starlino** [Links2004/arduinoWebSockets#343]
My compiler is issuing following warnings.  Compiler warnings in libraries distract from warnings in user code .

1)

I think it is common practice now to define  a  
default:   break ;
line in the switch statements.

.piolibdeps\WebSockets_ID549\src\WebSocketsServer.cpp: In member function 'virtual void WebSocketsServer::messageReceived(WSclient_t*, WSopcode_t, uint8_t*, size_t, bool)':
.piolibdeps\WebSockets_ID549\src\WebSocketsServer.cpp:483:11: warning: enumeration value 'WSop_close' not handled in switch [-Wswitch]
switch(opcode) {
^
.piolibdeps\WebSockets_ID549\src\WebSocketsServer.cpp:483:11: warning: enumeration value 'WSop_ping' not handled in switch [-Wswitch]
.piolibdeps\WebSockets_ID549\src\WebSocketsServer.cpp:483:11: warning: enumeration value 'WSop_pong' not handled in switch [-Wswitch]

2) 
Additionally there is an unused variable:

.piolibdeps\WebSockets_ID549\src\WebSockets.cpp: In member function 'void WebSockets::handleWebsocketPayloadCb(WSclient_t*, bool, uint8_t*)':
.piolibdeps\WebSockets_ID549\src\WebSockets.cpp:443:26: warning: variable 'reasonCode' set but not used [-Wunused-but-set-variable]
uint16_t reasonCode = 1000;

Thank you !!!

**Comment by Links2004** [comment]
this where fixed with this commit:
https://github.com/Links2004/arduinoWebSockets/commit/bde97179bf9f8d3c39235d751816ae9358984c2c

**Comment by starlino** [comment]
Thanks, I still get one warning with the HEAD version.

variable 'reasonCode' set but not used [-Wunused-but-set-variable]

How about  isolating this block  in 


#ifndef NODEBUG_WEBSOCKETS
......................
#endif

since it's for debug only ??? 


```
       uint16_t reasonCode = 1000;
                if(header->payloadLen >= 2) {
                    reasonCode = payload[0] << 8 | payload[1];
                }

                DEBUG_WEBSOCKETS("[WS][%d][handleWebsocket] get ask for close. Code: %d", client->num, reasonCode);
                if(header->payloadLen > 2) {
                    DEBUG_WEBSOCKETS(" (%s)\n", (payload + 2));
                } else {
                    DEBUG_WEBSOCKETS("\n");
                }
```
